stages:
  - java-build
  - docker-build
  - kubernetes-diff
  - kubernetes-apply

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
    -DskipTests=true
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    -DinstallAtEnd=true
    -DdeployAtEnd=true
  DOCKER_HOST: tcp://docker-dind:2375

java-build:
  # select the most appropriate image for your project
  image: harbor.solumesl.com/maven/maven:3.8-openjdk-11
  stage: java-build
  # Cache downloaded dependencies and plugins between builds.
  # The key here separates one cache per branch/tag ($CI_COMMIT_REF_SLUG)
  cache:
    key: "maven-$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository
  script:
    - mvn $MAVEN_CLI_OPTS clean install package -s settings.xml
  artifacts:
    name: "Maven artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    paths:
      - "**/target"
  only:
    refs:
      - main
      - master
      - feature/cicd
    changes:
      # - ".gitlab-ci.yml"
      - "pom.xml"
      - "settings.xml"
      - ".docker-build/*"
      - ".docker-build/**/*"
      - "src/*"
      - "src/**/*"

docker-build:
  stage: docker-build
  image: harbor.solumesl.com/docker/docker:20.10.12-git
  before_script:
    - docker info
  script:
    - .docker-build/docker-build.sh
  # when: manual
  only:
    refs:
      - main
      - master
      - feature/cicd
    changes:
      # - ".gitlab-ci.yml"
      - "pom.xml"
      - ".docker-build/*"
      - ".docker-build/**/*"
      - "src/*"
      - "src/**/*"

kubernetes-diff:
  stage: kubernetes-diff
  image: harbor.solumesl.com/alpine/k8s:1.22.9
  script:
    - .deploy/new_deploy.sh diff
  # when: manual
  only:
    refs:
      - main
      - master
      - feature/cicd
    changes:
      - ".gitlab-ci.yml"
      - "pom.xml"
      - ".deploy/*"
      - ".deploy/**/*"
      - ".dockerbuild/*"
      - ".dockerbuild/**/*"
      - "src/*"
      - "src/**/*"

kubernetes-apply:
  stage: kubernetes-apply
  image: harbor.solumesl.com/alpine/k8s:1.22.9
  script:
    - .deploy/new_deploy.sh apply
  when: manual
  only:
    refs:
      - main
      - master
      - feature/cicd
    changes:
      - ".gitlab-ci.yml"
      - "pom.xml"
      - ".deploy/*"
      - ".deploy/**/*"
      - ".dockerbuild/*"
      - ".dockerbuild/**/*"
      - "src/*"
      - "src/**/*"
